<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class LandSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run(): void
    {
        DB::table('lands')->delete();

        $data = [
        ['id'=>1,'country_id' => 17,'slug'=>'-','name'=>'-','polish'=>0,'created_at' => date('Y-m-d H:i:s'), 'updated_at' =>date('Y-m-d H:i:s')],
        ['id'=>2,'country_id' => 1,'slug'=>'devon','name'=>'Devon','polish'=>0,'created_at' => date('Y-m-d H:i:s'), 'updated_at' =>date('Y-m-d H:i:s')],
        ['id'=>3,'country_id' => 1,'slug'=>'gloucestershire','name'=>'Gloucestershire','polish'=>0,'created_at' => date('Y-m-d H:i:s'), 'updated_at' =>date('Y-m-d H:i:s')],
        ['id'=>4,'country_id' => 1,'slug'=>'greater-london','name'=>'Greater London','polish'=>0,'created_at' => date('Y-m-d H:i:s'), 'updated_at' =>date('Y-m-d H:i:s')],
        ['id'=>5,'country_id' => 1,'slug'=>'hampshire','name'=>'Hampshire','polish'=>0,'created_at' => date('Y-m-d H:i:s'), 'updated_at' =>date('Y-m-d H:i:s')],
        ['id'=>6,'country_id' => 1,'slug'=>'leicestershire','name'=>'Leicestershire','polish'=>0,'created_at' => date('Y-m-d H:i:s'), 'updated_at' =>date('Y-m-d H:i:s')],
        ['id'=>7,'country_id' => 1,'slug'=>'oxfordshire','name'=>'Oxfordshire','polish'=>0,'created_at' => date('Y-m-d H:i:s'), 'updated_at' =>date('Y-m-d H:i:s')],
        ['id'=>8,'country_id' => 1,'slug'=>'norfolk','name'=>'Norfolk','polish'=>0,'created_at' => date('Y-m-d H:i:s'),'updated_at' =>date('Y-m-d H:i:s')],
        ['id'=>9,'country_id' => 1,'slug'=>'west-midlands','name'=>'West Midlands','polish'=>0,'created_at' => date('Y-m-d H:i:s'), 'updated_at' =>date('Y-m-d H:i:s')],
        ['id'=>10,'country_id' => 1,'slug'=>'west-yorkshire','name'=>'West Yorkshire','polish'=>0,'created_at' => date('Y-m-d H:i:s'), 'updated_at' =>date('Y-m-d H:i:s')],

        ['id'=>11,'country_id' => 2,'slug'=>'burgenland','name'=>'Burgenland','polish'=>0,'created_at' => date('Y-m-d H:i:s'), 'updated_at' =>date('Y-m-d H:i:s')],
        ['id'=>12,'country_id' => 2,'slug'=>'karnten','name'=>'Kärnten','polish'=>0,'created_at' => date('Y-m-d H:i:s'), 'updated_at' =>date('Y-m-d H:i:s')],
        ['id'=>13,'country_id' => 2,'slug'=>'niederosterreich','name'=>'Niederösterreich','polish'=>0,'created_at' => date('Y-m-d H:i:s'), 'updated_at' =>date('Y-m-d H:i:s')],
        ['id'=>14,'country_id' => 2,'slug'=>'oberösterreich','name'=>'Oberösterreich','polish'=>0,'created_at' => date('Y-m-d H:i:s'), 'updated_at' =>date('Y-m-d H:i:s')],
        ['id'=>15,'country_id' => 2,'slug'=>'salzburg','name'=>'Salzburg','polish'=>0,'created_at' => date('Y-m-d H:i:s'), 'updated_at' =>date('Y-m-d H:i:s')],
        ['id'=>16,'country_id' => 2,'slug'=>'steiermark','name'=>'Steiermark','polish'=>0,'created_at' => date('Y-m-d H:i:s'), 'updated_at' =>date('Y-m-d H:i:s')],
        ['id'=>17,'country_id' => 2,'slug'=>'tirol','name'=>'Tirol','polish'=>0,'created_at' => date('Y-m-d H:i:s'), 'updated_at' =>date('Y-m-d H:i:s')],
        ['id'=>18,'country_id' => 2,'slug'=>'vorarlberg','name'=>'Vorarlberg','polish'=>0,'created_at' => date('Y-m-d H:i:s'), 'updated_at' =>date('Y-m-d H:i:s')],
        ['id'=>19,'country_id' => 2,'slug'=>'wien','name'=>'Wien','polish'=>0,'created_at' => date('Y-m-d H:i:s'), 'updated_at' =>date('Y-m-d H:i:s')],


        ['id'=>20,'country_id' => 3,'slug'=>'brabant-walloon','name'=>'Brabant-Walloon','polish'=>0,'created_at' => date('Y-m-d H:i:s'), 'updated_at' =>date('Y-m-d H:i:s')],
        ['id'=>21,'country_id' => 3,'slug'=>'liege','name'=>'Liège','polish'=>0,'created_at' => date('Y-m-d H:i:s'), 'updated_at' =>date('Y-m-d H:i:s')],


        ['id'=>22,'country_id' => 4,'slug'=>'grand-est','name'=>'Grand Est','polish'=>0,'created_at' => date('Y-m-d H:i:s'), 'updated_at' =>date('Y-m-d H:i:s')],
        ['id'=>23,'country_id' => 4,'slug'=>'Île-de-france','name'=>'Île-de-France','polish'=>0,'created_at' => date('Y-m-d H:i:s'), 'updated_at' =>date('Y-m-d H:i:s')],
        ['id'=>24,'country_id' => 4,'slug'=>'centre-val-de-loire','name'=>'Centre-Val de Loire','polish'=>0,'created_at' => date('Y-m-d H:i:s'), 'updated_at' =>date('Y-m-d H:i:s')],
        ['id'=>25,'country_id' => 4,'slug'=>'occitanie','name'=>'Occitanie','polish'=>0,'created_at' => date('Y-m-d H:i:s'), 'updated_at' =>date('Y-m-d H:i:s')],


        ['id'=>26,'country_id' => 5,'slug'=>'cataluna','name'=>'Cataluña','polish'=>0,'created_at' => date('Y-m-d H:i:s'), 'updated_at' =>date('Y-m-d H:i:s')],
        ['id'=>27,'country_id' => 5,'slug'=>'valencia','name'=>'Valencia','polish'=>0,'created_at' => date('Y-m-d H:i:s'), 'updated_at' =>date('Y-m-d H:i:s')],
        ['id'=>28,'country_id' => 5,'slug'=>'islas-canarias','name'=>'Islas Canarias','polish'=>0,'created_at' => date('Y-m-d H:i:s'), 'updated_at' =>date('Y-m-d H:i:s')],
        ['id'=>29,'country_id' => 5,'slug'=>'islas-baleares','name'=>'Islas Baleares','polish'=>0,'created_at' => date('Y-m-d H:i:s'), 'updated_at' =>date('Y-m-d H:i:s')],
        ['id'=>30,'country_id' => 5,'slug'=>'andalucía','name'=>'Andalucía','polish'=>0,'created_at' => date('Y-m-d H:i:s'), 'updated_at' =>date('Y-m-d H:i:s')],

        ['id'=>31,'country_id' => 6,'slug'=>'drenthe','name'=>'Drenthe','polish'=>0,'created_at' => date('Y-m-d H:i:s'), 'updated_at' =>date('Y-m-d H:i:s')],
        ['id'=>32,'country_id' => 6,'slug'=>'flevoland','name'=>'Flevoland','polish'=>0,'created_at' => date('Y-m-d H:i:s'), 'updated_at' =>date('Y-m-d H:i:s')],
        ['id'=>33,'country_id' => 6,'slug'=>'fryslan','name'=>'Fryslân','polish'=>0,'created_at' => date('Y-m-d H:i:s'), 'updated_at' =>date('Y-m-d H:i:s')],
        ['id'=>34,'country_id' => 6,'slug'=>'gelderland','name'=>'Gelderland','polish'=>0,'created_at' => date('Y-m-d H:i:s'), 'updated_at' =>date('Y-m-d H:i:s')],
        ['id'=>35,'country_id' => 6,'slug'=>'groningen','name'=>'Groningen','polish'=>0,'created_at' => date('Y-m-d H:i:s'), 'updated_at' =>date('Y-m-d H:i:s')],
        ['id'=>36,'country_id' => 6,'slug'=>'limburg','name'=>'Limburg','polish'=>0,'created_at' => date('Y-m-d H:i:s'), 'updated_at' =>date('Y-m-d H:i:s')],
        ['id'=>37,'country_id' => 6,'slug'=>'noord-brabant','name'=>'Noord-Brabant','polish'=>0,'created_at' => date('Y-m-d H:i:s'), 'updated_at' =>date('Y-m-d H:i:s')],
        ['id'=>38,'country_id' => 6,'slug'=>'noord-holland','name'=>'Noord-Holland','polish'=>0,'created_at' => date('Y-m-d H:i:s'), 'updated_at' =>date('Y-m-d H:i:s')],
        ['id'=>39,'country_id' => 6,'slug'=>'overijssel','name'=>'Overijssel','polish'=>0,'created_at' => date('Y-m-d H:i:s'), 'updated_at' =>date('Y-m-d H:i:s')],
        ['id'=>40,'country_id' => 6,'slug'=>'utrecht','name'=>'Utrecht','polish'=>0,'created_at' => date('Y-m-d H:i:s'), 'updated_at' =>date('Y-m-d H:i:s')],
        ['id'=>41,'country_id' => 6,'slug'=>'zeeland','name'=>'Zeeland','polish'=>0,'created_at' => date('Y-m-d H:i:s'), 'updated_at' =>date('Y-m-d H:i:s')],
        ['id'=>42,'country_id' => 6,'slug'=>'zuid-holland','name'=>'Zuid-Holland','polish'=>0,'created_at' => date('Y-m-d H:i:s'), 'updated_at' =>date('Y-m-d H:i:s')],

        ['id'=>43,'country_id' => 9,'slug'=>'capellen','name'=>'Capellen','polish'=>0,'created_at' => date('Y-m-d H:i:s'), 'updated_at' =>date('Y-m-d H:i:s')],
        ['id'=>44,'country_id' => 9,'slug'=>'clervaux','name'=>'Clervaux','polish'=>0,'created_at' => date('Y-m-d H:i:s'), 'updated_at' =>date('Y-m-d H:i:s')],
        ['id'=>45,'country_id' => 9,'slug'=>'diekirch','name'=>'Diekirch','polish'=>0,'created_at' => date('Y-m-d H:i:s'), 'updated_at' =>date('Y-m-d H:i:s')],
        ['id'=>46,'country_id' => 9,'slug'=>'echternach','name'=>'Echternach','polish'=>0,'created_at' => date('Y-m-d H:i:s'), 'updated_at' =>date('Y-m-d H:i:s')],
        ['id'=>47,'country_id' => 9,'slug'=>'esch-sur-alzette','name'=>'Esch-sur-Alzette','polish'=>0,'created_at' => date('Y-m-d H:i:s'), 'updated_at' =>date('Y-m-d H:i:s')],
        ['id'=>48,'country_id' => 9,'slug'=>'grevenmacher','name'=>'Grevenmacher','polish'=>0,'created_at' => date('Y-m-d H:i:s'), 'updated_at' =>date('Y-m-d H:i:s')],
        ['id'=>49,'country_id' => 9,'slug'=>'luksemburg','name'=>'Luksemburg','polish'=>0,'created_at' => date('Y-m-d H:i:s'), 'updated_at' =>date('Y-m-d H:i:s')],
        ['id'=>50,'country_id' => 9,'slug'=>'mersch','name'=>'Mersch','polish'=>0,'created_at' => date('Y-m-d H:i:s'), 'updated_at' =>date('Y-m-d H:i:s')],
        ['id'=>51,'country_id' => 9,'slug'=>'redange','name'=>'Redange','polish'=>0,'created_at' => date('Y-m-d H:i:s'), 'updated_at' =>date('Y-m-d H:i:s')],
        ['id'=>52,'country_id' => 9,'slug'=>'vianden','name'=>'Vianden','polish'=>0,'created_at' => date('Y-m-d H:i:s'), 'updated_at' =>date('Y-m-d H:i:s')],

        ['id'=>53,'country_id' => 10,'slug'=>'baden-wurttemberg-bw','name'=>'Baden-Württemberg (BW)','polish'=>0,'created_at' => date('Y-m-d H:i:s'), 'updated_at' =>date('Y-m-d H:i:s')],
        ['id'=>54,'country_id' => 10,'slug'=>'badenia-wirtembergia','name'=>'Badenia-Wirtembergia','polish'=>0,'created_at' => date('Y-m-d H:i:s'), 'updated_at' =>date('Y-m-d H:i:s')],
        ['id'=>55,'country_id' => 10,'slug'=>'bayern-by','name'=>'Bayern (BY)','polish'=>0,'created_at' => date('Y-m-d H:i:s'), 'updated_at' =>date('Y-m-d H:i:s')],
        ['id'=>56,'country_id' => 10,'slug'=>'berlin-be','name'=>'Berlin (BE)','polish'=>0,'created_at' => date('Y-m-d H:i:s'), 'updated_at' =>date('Y-m-d H:i:s')],
        ['id'=>57,'country_id' => 10,'slug'=>'brandenburg-bb','name'=>'Brandenburg (BB)','polish'=>0,'created_at' => date('Y-m-d H:i:s'), 'updated_at' =>date('Y-m-d H:i:s')],
        ['id'=>58,'country_id' => 10,'slug'=>'bremen-hb','name'=>'Bremen (HB)','polish'=>0,'created_at' => date('Y-m-d H:i:s'), 'updated_at' =>date('Y-m-d H:i:s')],
        ['id'=>59,'country_id' => 10,'slug'=>'hamburg-hh','name'=>'Hamburg (HH)','polish'=>0,'created_at' => date('Y-m-d H:i:s'), 'updated_at' =>date('Y-m-d H:i:s')],
        ['id'=>60,'country_id' => 10,'slug'=>'hessen-he','name'=>'Hessen (HE)','polish'=>0,'created_at' => date('Y-m-d H:i:s'), 'updated_at' =>date('Y-m-d H:i:s')],
        ['id'=>61,'country_id' => 10,'slug'=>'mecklenburg-vorpommern-mw','name'=>'Mecklenburg-Vorpommern (MW)','polish'=>0,'created_at' => date('Y-m-d H:i:s'), 'updated_at' =>date('Y-m-d H:i:s')],
        ['id'=>62,'country_id' => 10,'slug'=>'niedersachsen-ni','name'=>'Niedersachsen (NI)','polish'=>0,'created_at' => date('Y-m-d H:i:s'), 'updated_at' =>date('Y-m-d H:i:s')],
        ['id'=>63,'country_id' => 10,'slug'=>'nordrhein-westfalen-nw','name'=>'Nordrhein-Westfalen (NW)','polish'=>0,'created_at' => date('Y-m-d H:i:s'), 'updated_at' =>date('Y-m-d H:i:s')],
        ['id'=>64,'country_id' => 10,'slug'=>'rheinland-Pfalz-rp','name'=>'Rheinland-Pfalz (RP)','polish'=>0,'created_at' => date('Y-m-d H:i:s'), 'updated_at' =>date('Y-m-d H:i:s')],
        ['id'=>65,'country_id' => 10,'slug'=>'saarland-sl','name'=>'Saarland (SL)','polish'=>0,'created_at' => date('Y-m-d H:i:s'), 'updated_at' =>date('Y-m-d H:i:s')],
        ['id'=>66,'country_id' => 10,'slug'=>'sachsen-sn','name'=>'Sachsen (SN)','polish'=>0,'created_at' => date('Y-m-d H:i:s'), 'updated_at' =>date('Y-m-d H:i:s')],
        ['id'=>67,'country_id' => 10,'slug'=>'sachsen-Anhalt-st','name'=>'Sachsen-Anhalt (ST)','polish'=>0,'created_at' => date('Y-m-d H:i:s'), 'updated_at' =>date('Y-m-d H:i:s')],
        ['id'=>68,'country_id' => 10,'slug'=>'schleswig-holstein-sh','name'=>'Schleswig-Holstein (SH)','polish'=>0,'created_at' => date('Y-m-d H:i:s'), 'updated_at' =>date('Y-m-d H:i:s')],
        ['id'=>69,'country_id' => 10,'slug'=>'thüringen-th','name'=>'Thüringen (TH)','polish'=>0,'created_at' => date('Y-m-d H:i:s'), 'updated_at' =>date('Y-m-d H:i:s')],
        ['id'=>70,'country_id' => 11,'slug'=>'dolnośląskie-dsl','name'=>'Dolnośląskie (DŚL)','polish'=>1,'created_at' => date('Y-m-d H:i:s'), 'updated_at' =>date('Y-m-d H:i:s')],
        ['id'=>71,'country_id' => 11,'slug'=>'kujawsko-pomorskie-kp','name'=>'Kujawsko-Pomorskie (K-P)','polish'=>1,'created_at' => date('Y-m-d H:i:s'), 'updated_at' =>date('Y-m-d H:i:s')],
        ['id'=>72,'country_id' => 11,'slug'=>'lubelskie-lbl','name'=>'Lubelskie (LBL)','polish'=>1,'created_at' => date('Y-m-d H:i:s'), 'updated_at' =>date('Y-m-d H:i:s')],
        ['id'=>73,'country_id' => 11,'slug'=>'lubuskie-lbu','name'=>'Lubuskie (LBU)','polish'=>1,'created_at' => date('Y-m-d H:i:s'), 'updated_at' =>date('Y-m-d H:i:s')],
        ['id'=>74,'country_id' => 11,'slug'=>'lodzkie-ldz','name'=>'Łódzkie (ŁDZ)','polish'=>1,'created_at' => date('Y-m-d H:i:s'), 'updated_at' =>date('Y-m-d H:i:s')],
        ['id'=>75,'country_id' => 11,'slug'=>'malopolskie-mlp','name'=>'Małopolskie (MŁP)','polish'=>1,'created_at' => date('Y-m-d H:i:s'), 'updated_at' =>date('Y-m-d H:i:s')],
        ['id'=>76,'country_id' => 11,'slug'=>'mazowieckie-maz','name'=>'Mazowieckie (MAZ)','polish'=>1,'created_at' => date('Y-m-d H:i:s'), 'updated_at' =>date('Y-m-d H:i:s')],
        ['id'=>77,'country_id' => 11,'slug'=>'opolskie-opo','name'=>'Opolskie (OPO)','polish'=>1,'created_at' => date('Y-m-d H:i:s'), 'updated_at' =>date('Y-m-d H:i:s')],
        ['id'=>78,'country_id' => 11,'slug'=>'podkarpackie-pkr','name'=>'Podkarpackie (PKR)','polish'=>1,'created_at' => date('Y-m-d H:i:s'), 'updated_at' =>date('Y-m-d H:i:s')],
        ['id'=>79,'country_id' => 11,'slug'=>'podlaskie-pdl','name'=>'Podlaskie ( PDL)','polish'=>1,'created_at' => date('Y-m-d H:i:s'), 'updated_at' =>date('Y-m-d H:i:s')],
        ['id'=>80,'country_id' => 11,'slug'=>'pomorskie-pom','name'=>'Pomorskie (POM)','polish'=>1,'created_at' => date('Y-m-d H:i:s'), 'updated_at' =>date('Y-m-d H:i:s')],
        ['id'=>81,'country_id' => 11,'slug'=>'slaskie-sl','name'=>'Śląskie (ŚL)','polish'=>1,'created_at' => date('Y-m-d H:i:s'), 'updated_at' =>date('Y-m-d H:i:s')],
        ['id'=>82,'country_id' => 11,'slug'=>'swietokrzyskie-sw','name'=>'Świętokrzyskie (ŚW)','polish'=>1,'created_at' => date('Y-m-d H:i:s'), 'updated_at' =>date('Y-m-d H:i:s')],
        ['id'=>83,'country_id' => 11,'slug'=>'warminsko-mazurskie-wm','name'=>'Warmińsko-Mazurskie (WM)','polish'=>1,'created_at' => date('Y-m-d H:i:s'), 'updated_at' =>date('Y-m-d H:i:s')],
        ['id'=>84,'country_id' => 11,'slug'=>'wielkopolskie-wlkp','name'=>'Wielkopolskie (WLKP)','polish'=>1,'created_at' => date('Y-m-d H:i:s'), 'updated_at' =>date('Y-m-d H:i:s')],
        ['id'=>85,'country_id' => 11,'slug'=>'zachodniopomorskie-zpm','name'=>'Zachodniopomorskie (ZPM)','polish'=>1,'created_at' => date('Y-m-d H:i:s'), 'updated_at' =>date('Y-m-d H:i:s')],
        ['id'=>86,'country_id' => 12,'slug'=>'aberdeenshire','name'=>'Aberdeenshire','polish'=>1,'created_at' => date('Y-m-d H:i:s'), 'updated_at' =>date('Y-m-d H:i:s')],
        ['id'=>87,'country_id' => 13,'slug'=>'vaud','name'=>'Vaud','polish'=>0,'created_at' => date('Y-m-d H:i:s'), 'updated_at' =>date('Y-m-d H:i:s')],
        ['id'=>88,'country_id' => 13,'slug'=>'appenzell-innerrhoden','name'=>'Appenzell Innerrhoden','polish'=>0,'created_at' => date('Y-m-d H:i:s'), 'updated_at' =>date('Y-m-d H:i:s')],
        ['id'=>89,'country_id' => 13,'slug'=>'bazylea-miasto','name'=>'Bazylea-Miasto','polish'=>0,'created_at' => date('Y-m-d H:i:s'), 'updated_at' =>date('Y-m-d H:i:s')],
        ['id'=>90,'country_id' => 13,'slug'=>'berno','name'=>'Berno','polish'=>0,'created_at' => date('Y-m-d H:i:s'), 'updated_at' =>date('Y-m-d H:i:s')],
        ['id'=>91,'country_id' => 13,'slug'=>'lucerna','name'=>'Lucerna','polish'=>0,'created_at' => date('Y-m-d H:i:s'), 'updated_at' =>date('Y-m-d H:i:s')],
        ['id'=>92,'country_id' => 13,'slug'=>'zurych','name'=>'Zurych','polish'=>0,'created_at' => date('Y-m-d H:i:s'), 'updated_at' =>date('Y-m-d H:i:s')],
        ['id'=>93,'country_id' => 3,'slug'=>'oost-vlaanderen','name'=>'Oost-Vlaanderen','polish'=>0,'created_at' =>date('Y-m-d H:i:s'), 'updated_at' =>date('Y-m-d H:i:s')],
        ['id'=>94,'country_id' => 4,'slug'=>'nouvelle-aquitaine','name'=>'Nouvelle-Aquitaine','polish'=>0,'created_at'=>date('Y-m-d H:i:s'), 'updated_at' =>date('Y-m-d H:i:s')],
        ['id'=>95,'country_id' => 4,'slug'=>'hauts-de-france','name'=>'Hauts-de-France','polish'=>0,'created_at'=>date('Y-m-d H:i:s'), 'updated_at' =>date('Y-m-d H:i:s')],
        ['id'=>96,'country_id' => 4,'slug'=>'bretagne','name'=>'Bretagne','polish'=>0,'created_at'=>date('Y-m-d H:i:s'), 'updated_at' =>date('Y-m-d H:i:s')],
        ['id'=>97,'country_id' => 4,'slug'=>'bourgogne-franche-comte','name'=>'Bourgogne-Franche-Comté','polish'=>0,'created_at'=>date('Y-m-d H:i:s'), 'updated_at' =>date('Y-m-d H:i:s')],
        ['id'=>98,'country_id' => 4,'slug'=>'normandie','name'=>'Normandie','polish'=>0,'created_at'=>date('Y-m-d H:i:s'), 'updated_at' =>date('Y-m-d H:i:s')],
        ['id'=>99,'country_id' => 4,'slug'=>'corse','name'=>'Corse','polish'=>0,'created_at'=>date('Y-m-d H:i:s'), 'updated_at' =>date('Y-m-d H:i:s')],
        ['id'=>100,'country_id' => 4,'slug'=>'auvergne-rhone-alpes','name'=>'Auvergne-Rhône-Alpes','polish'=>0,'created_at'=>date('Y-m-d H:i:s'), 'updated_at' =>date('Y-m-d H:i:s')],
        ['id'=>101,'country_id' => 4,'slug'=>'provence-alpes-cote-dazur','name'=>'Provence-Alpes-Côte d’Azur','polish'=>0,'created_at'=>date('Y-m-d H:i:s'), 'updated_at' =>date('Y-m-d H:i:s')],
        ['id'=>102,'country_id' => 4,'slug'=>'centre-val-de-loire','name'=>'Centre-Val de Loire','polish'=>0,'created_at'=>date('Y-m-d H:i:s'), 'updated_at' =>date('Y-m-d H:i:s')],
        ['id'=>103,'country_id' => 5,'slug'=>'aragon','name'=>'Aragón','polish'=>0,'created_at'=>date('Y-m-d H:i:s'), 'updated_at' =>date('Y-m-d H:i:s')],
        ['id'=>104,'country_id' => 5,'slug'=>'principado-de-asturias','name'=>'Principado de Asturias','polish'=>0,'created_at'=>date('Y-m-d H:i:s'), 'updated_at' =>date('Y-m-d H:i:s')],
        ['id'=>105,'country_id' => 5,'slug'=>'pais-vasco-comunidad-autonoma-vasca','name'=>'País Vasco, Comunidad Autónoma Vasca','polish'=>0,'created_at'=>date('Y-m-d H:i:s'), 'updated_at' =>date('Y-m-d H:i:s')],
        ['id'=>106,'country_id' => 5,'slug'=>'cantabria','name'=>'Cantabria','polish'=>0,'created_at'=>date('Y-m-d H:i:s'), 'updated_at' =>date('Y-m-d H:i:s')],
        ['id'=>107,'country_id' => 5,'slug'=>'castilla-la-mancha','name'=>'Castilla-La Mancha','polish'=>0,'created_at'=>date('Y-m-d H:i:s'), 'updated_at' =>date('Y-m-d H:i:s')],
        ['id'=>108,'country_id' => 5,'slug'=>'castilla-y-leon','name'=>'Castilla y León','polish'=>0,'created_at'=>date('Y-m-d H:i:s'), 'updated_at' =>date('Y-m-d H:i:s')],
        ['id'=>109,'country_id' => 5,'slug'=>'extremadura','name'=>'Extremadura','polish'=>0,'created_at'=>date('Y-m-d H:i:s'), 'updated_at' =>date('Y-m-d H:i:s')],
        ['id'=>110,'country_id' => 5,'slug'=>'galicia','name'=>'Galicia','polish'=>0,'created_at'=>date('Y-m-d H:i:s'), 'updated_at' =>date('Y-m-d H:i:s')],
        ['id'=>111,'country_id' => 5,'slug'=>'la-rioja','name'=>'La Rioja','polish'=>0,'created_at'=>date('Y-m-d H:i:s'), 'updated_at' =>date('Y-m-d H:i:s')],
        ['id'=>112,'country_id' => 5,'slug'=>'madrid-comunidad-de-madrid','name'=>'Madrid, Comunidad de Madrid','polish'=>0,'created_at'=>date('Y-m-d H:i:s'), 'updated_at' =>date('Y-m-d H:i:s')],
        ['id'=>113,'country_id' => 5,'slug'=>'region-de-murcia','name'=>'Región de Murcia','polish'=>0,'created_at'=>date('Y-m-d H:i:s'), 'updated_at' =>date('Y-m-d H:i:s')],
        ['id'=>114,'country_id' => 5,'slug'=>'comunidad-foral-de-navarra','name'=>'Comunidad Foral de Navarra','polish'=>0,'created_at'=>date('Y-m-d H:i:s'), 'updated_at' =>date('Y-m-d H:i:s')],
        ['id'=>115,'country_id' => 7,'slug'=>'contae-atha-cliath','name'=>'Contae Átha Cliath','polish'=>0,'created_at'=>date('Y-m-d H:i:s'), 'updated_at' =>date('Y-m-d H:i:s')],
        ['id'=>116,'country_id' => 7,'slug'=>'contae-chill-mhantain','name'=>'Contae Chill Mhantáin','polish'=>0,'created_at'=>date('Y-m-d H:i:s'), 'updated_at' =>date('Y-m-d H:i:s')],
        ['id'=>117,'country_id' => 7,'slug'=>'contae-loch-garman','name'=>'Contae Loch Garman','polish'=>0,'created_at'=>date('Y-m-d H:i:s'), 'updated_at' =>date('Y-m-d H:i:s')],
        ['id'=>118,'country_id' => 7,'slug'=>'nocontae-cheatharlach','name'=>'Contae Cheatharlach','polish'=>0,'created_at'=>date('Y-m-d H:i:s'), 'updated_at' =>date('Y-m-d H:i:s')],
        ['id'=>119,'country_id' => 7,'slug'=>'contae-chill-dara','name'=>'Contae Chill Dara','polish'=>0,'created_at'=>date('Y-m-d H:i:s'), 'updated_at' =>date('Y-m-d H:i:s')],
        ['id'=>120,'country_id' => 7,'slug'=>'contae-na-mi','name'=>'Contae na Mí','polish'=>0,'created_at'=>date('Y-m-d H:i:s'), 'updated_at' =>date('Y-m-d H:i:s')],
        ['id'=>121,'country_id' => 7,'slug'=>'contae-lu','name'=>'Contae Lu','polish'=>0,'created_at'=>date('Y-m-d H:i:s'), 'updated_at' =>date('Y-m-d H:i:s')],
        ['id'=>122,'country_id' => 7,'slug'=>'contae-mhuineachain','name'=>'Contae Mhuineacháin','polish'=>0,'created_at'=>date('Y-m-d H:i:s'), 'updated_at' =>date('Y-m-d H:i:s')],
        ['id'=>123,'country_id' => 7,'slug'=>'contae-chabhain','name'=>'Contae Chabháin','polish'=>0,'created_at'=>date('Y-m-d H:i:s'), 'updated_at' =>date('Y-m-d H:i:s')],
        ['id'=>124,'country_id' => 7,'slug'=>'contae-an-longfoirt','name'=>'Contae an Longfoirt','polish'=>0,'created_at'=>date('Y-m-d H:i:s'), 'updated_at' =>date('Y-m-d H:i:s')],
        ['id'=>125,'country_id' => 7,'slug'=>'contae-na-hiarmhi','name'=>'Contae na hIarmhí','polish'=>0,'created_at'=>date('Y-m-d H:i:s'), 'updated_at' =>date('Y-m-d H:i:s')],
        ['id'=>126,'country_id' => 7,'slug'=>'contae-uibh-fhaili','name'=>'Contae Uíbh Fhailí','polish'=>0,'created_at'=>date('Y-m-d H:i:s'), 'updated_at' =>date('Y-m-d H:i:s')],
        ['id'=>127,'country_id' => 7,'slug'=>'contae-laoise','name'=>'Contae Laoise','polish'=>0,'created_at'=>date('Y-m-d H:i:s'), 'updated_at' =>date('Y-m-d H:i:s')],
        ['id'=>128,'country_id' => 7,'slug'=>'contae-chill-chainnigh','name'=>'Contae Chill Chainnigh','polish'=>0,'created_at'=>date('Y-m-d H:i:s'), 'updated_at' =>date('Y-m-d H:i:s')],
        ['id'=>129,'country_id' => 7,'slug'=>'contae-phort-lairge','name'=>'Contae Phort Láirge','polish'=>0,'created_at'=>date('Y-m-d H:i:s'), 'updated_at' =>date('Y-m-d H:i:s')],
        ['id'=>130,'country_id' => 7,'slug'=>'contae-chorcai','name'=>'Contae Chorcaí','polish'=>0,'created_at'=>date('Y-m-d H:i:s'), 'updated_at' =>date('Y-m-d H:i:s')],
        ['id'=>131,'country_id' => 7,'slug'=>'contae-chiarrai','name'=>'Contae Chiarraí','polish'=>0,'created_at'=>date('Y-m-d H:i:s'), 'updated_at' =>date('Y-m-d H:i:s')],
        ['id'=>132,'country_id' => 7,'slug'=>'contae-luimnigh','name'=>'Contae Luimnigh','polish'=>0,'created_at'=>date('Y-m-d H:i:s'), 'updated_at' =>date('Y-m-d H:i:s')],
        ['id'=>133,'country_id' => 7,'slug'=>'contae-thiobraid-arann','name'=>'Contae Thiobraid Árann','polish'=>0,'created_at'=>date('Y-m-d H:i:s'), 'updated_at' =>date('Y-m-d H:i:s')],
        ['id'=>134,'country_id' => 7,'slug'=>'contae-an-chlair','name'=>'Contae an Chláir','polish'=>0,'created_at'=>date('Y-m-d H:i:s'), 'updated_at' =>date('Y-m-d H:i:s')],
        ['id'=>135,'country_id' => 7,'slug'=>'contae-na-gaillimhe','name'=>'Contae na Gaillimhe','polish'=>0,'created_at'=>date('Y-m-d H:i:s'), 'updated_at' =>date('Y-m-d H:i:s')],
        ['id'=>136,'country_id' => 7,'slug'=>'contae-mhaigh-eo','name'=>'Contae Mhaigh Eo','polish'=>0,'created_at'=>date('Y-m-d H:i:s'), 'updated_at' =>date('Y-m-d H:i:s')],
        ['id'=>137,'country_id' => 7,'slug'=>'contae-ros-comain','name'=>'Contae Ros Comáin','polish'=>0,'created_at'=>date('Y-m-d H:i:s'), 'updated_at' =>date('Y-m-d H:i:s')],
        ['id'=>138,'country_id' => 7,'slug'=>'contae-shligigh','name'=>'Contae Shligigh','polish'=>0,'created_at'=>date('Y-m-d H:i:s'), 'updated_at' =>date('Y-m-d H:i:s')],
        ['id'=>139,'country_id' => 7,'slug'=>'contae-liatroma','name'=>'Contae Liatroma','polish'=>0,'created_at'=>date('Y-m-d H:i:s'), 'updated_at' =>date('Y-m-d H:i:s')],
        ['id'=>140,'country_id' => 7,'slug'=>'contae-dhun-na-ngall','name'=>'Contae Dhún na nGall','polish'=>0,'created_at'=>date('Y-m-d H:i:s'), 'updated_at' =>date('Y-m-d H:i:s')],
        ['id'=>141,'country_id' => 8,'slug'=>'contae-fhear-manach','name'=>'Contae Fhear Manach','polish'=>0,'created_at'=>date('Y-m-d H:i:s'), 'updated_at' =>date('Y-m-d H:i:s')],
        ['id'=>142,'country_id' => 8,'slug'=>'contae-tir-eoghain','name'=>'Contae Tír Eoghain','polish'=>0,'created_at'=>date('Y-m-d H:i:s'), 'updated_at' =>date('Y-m-d H:i:s')],
        ['id'=>143,'country_id' => 8,'slug'=>'contae-dhoire','name'=>'Contae Dhoire','polish'=>0,'created_at'=>date('Y-m-d H:i:s'), 'updated_at' =>date('Y-m-d H:i:s')],
        ['id'=>144,'country_id' => 8,'slug'=>'contae-aontroma','name'=>'Contae Aontroma','polish'=>0,'created_at'=>date('Y-m-d H:i:s'), 'updated_at' =>date('Y-m-d H:i:s')],
        ['id'=>145,'country_id' => 8,'slug'=>'contae-an-duin','name'=>'Contae An Dúin','polish'=>0,'created_at'=>date('Y-m-d H:i:s'), 'updated_at' =>date('Y-m-d H:i:s')],
        ['id'=>146,'country_id' => 8,'slug'=>'contae-ard-mhacha','name'=>'Contae Ard Mhacha','polish'=>0,'created_at'=>date('Y-m-d H:i:s'), 'updated_at' =>date('Y-m-d H:i:s')],
        ['id'=>147,'country_id' => 13,'slug'=>'uri','name'=>'Uri','polish'=>0,'created_at'=>date('Y-m-d H:i:s'), 'updated_at' =>date('Y-m-d H:i:s')],
        ['id'=>148,'country_id' => 13,'slug'=>'schwyz','name'=>'Schwyz','polish'=>0,'created_at'=>date('Y-m-d H:i:s'), 'updated_at' =>date('Y-m-d H:i:s')],
        ['id'=>149,'country_id' => 13,'slug'=>'obwalden','name'=>'Obwalden','polish'=>0,'created_at'=>date('Y-m-d H:i:s'), 'updated_at' =>date('Y-m-d H:i:s')],
        ['id'=>150,'country_id' => 13,'slug'=>'nidwalden','name'=>'Nidwalden','polish'=>0,'created_at'=>date('Y-m-d H:i:s'), 'updated_at' =>date('Y-m-d H:i:s')],
        ['id'=>151,'country_id' => 13,'slug'=>'glarus','name'=>'Glarus','polish'=>0,'created_at'=>date('Y-m-d H:i:s'), 'updated_at' =>date('Y-m-d H:i:s')],
        ['id'=>152,'country_id' => 13,'slug'=>'zug','name'=>'Zug','polish'=>0,'created_at'=>date('Y-m-d H:i:s'), 'updated_at' =>date('Y-m-d H:i:s')],
        ['id'=>153,'country_id' => 13,'slug'=>'freiburg','name'=>'Freiburg','polish'=>0,'created_at'=>date('Y-m-d H:i:s'), 'updated_at' =>date('Y-m-d H:i:s')],
        ['id'=>154,'country_id' => 13,'slug'=>'solothurn','name'=>'Solothurn','polish'=>0,'created_at'=>date('Y-m-d H:i:s'), 'updated_at' =>date('Y-m-d H:i:s')],
        ['id'=>155,'country_id' => 13,'slug'=>'basel-landschaft','name'=>'Basel-Landschaft','polish'=>0,'created_at'=>date('Y-m-d H:i:s'), 'updated_at' =>date('Y-m-d H:i:s')],
        ['id'=>156,'country_id' => 13,'slug'=>'schaffhausen','name'=>'Schaffhausen','polish'=>0,'created_at'=>date('Y-m-d H:i:s'), 'updated_at' =>date('Y-m-d H:i:s')],
        ['id'=>157,'country_id' => 13,'slug'=>'appenzell-ausserrhoden','name'=>'Appenzell Ausserrhoden','polish'=>0,'created_at'=>date('Y-m-d H:i:s'), 'updated_at' =>date('Y-m-d H:i:s')],
        ['id'=>158,'country_id' => 13,'slug'=>'kanton-st-gallen','name'=>'Kanton St. Gallen','polish'=>0,'created_at'=>date('Y-m-d H:i:s'), 'updated_at' =>date('Y-m-d H:i:s')],
        ['id'=>159,'country_id' => 13,'slug'=>'graubunden','name'=>'Graubünden','polish'=>0,'created_at'=>date('Y-m-d H:i:s'), 'updated_at' =>date('Y-m-d H:i:s')],
        ['id'=>160,'country_id' => 13,'slug'=>'aargau','name'=>'Aargau','polish'=>0,'created_at'=>date('Y-m-d H:i:s'), 'updated_at' =>date('Y-m-d H:i:s')],
        ['id'=>161,'country_id' => 13,'slug'=>'thurgau','name'=>'Thurgau','polish'=>0,'created_at'=>date('Y-m-d H:i:s'), 'updated_at' =>date('Y-m-d H:i:s')],
        ['id'=>162,'country_id' => 13,'slug'=>'ticino','name'=>'Ticino','polish'=>0,'created_at'=>date('Y-m-d H:i:s'), 'updated_at' =>date('Y-m-d H:i:s')],
        ['id'=>163,'country_id' => 13,'slug'=>'wallis','name'=>'Wallis','polish'=>0,'created_at'=>date('Y-m-d H:i:s'), 'updated_at' =>date('Y-m-d H:i:s')],
        ['id'=>164,'country_id' => 13,'slug'=>'republik-und-kanton-neuenburg','name'=>'Republik und Kanton Neuenburg','polish'=>0,'created_at'=>date('Y-m-d H:i:s'), 'updated_at' =>date('Y-m-d H:i:s')],
        ['id'=>165,'country_id' => 13,'slug'=>'genf','name'=>'Genf','polish'=>0,'created_at'=>date('Y-m-d H:i:s'), 'updated_at' =>date('Y-m-d H:i:s')],
        ['id'=>166,'country_id' => 13,'slug'=>'jura','name'=>'Jura','polish'=>0,'created_at'=>date('Y-m-d H:i:s'), 'updated_at' =>date('Y-m-d H:i:s')],
        ['id'=>167,'country_id' => 13,'slug'=>'basel-stadt','name'=>'Basel-Stadt','polish'=>0,'created_at'=>date('Y-m-d H:i:s'), 'updated_at' =>date('Y-m-d H:i:s')],
        ['id'=>168,'country_id' => 3,'slug'=>'vlaams-gewest','name'=>'Vlaams Gewest','polish'=>0,'created_at'=>date('Y-m-d H:i:s'), 'updated_at' =>date('Y-m-d H:i:s')],
        ];

        DB::table('lands')->insert($data);
    }
}
